server:
  port: 8080

#my:
#  name: jimo
#  age: 19
  

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sqlcourse
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    suffix: .html
#    prefix: classpath:/templates/
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html


#spring: 
#  datasource:
#      url: jdbc:sqlserver://localhost:1433;databaseName=test
#      username: sa
#      password: AdminRoot1234
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver    
#  thymeleaf:
#    cache: false
#    suffix: .html
##    prefix: classpath:/templates/
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    content-type: text/html

#spring: 
#  freemarker:
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    suffix: .html

  
    
audience: 
  clientId: 098f6bcd4621d373cade4e832627b4f6  
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=  
  name: restapiuser  
  expiresSecond: 172800  
  
argments: 
  num: 3
  days: 3
  lock_days: 3
      
      
      
      
        